
# Makefile para socket-message-application

SRCS = client1 client2
OBJS = client1 client2

all: $(SRCS)


client1: client1.c
	gcc -o client1 client1.c 

client2: client2.c
	gcc -o client2 client2.c 

clean:
	rm -f $(OBJS)